# Site settings
title: VISION BY CURTIS Fotograf und Videograf aus Neusiedl am See 
email: "info@curtis.at"
description: "VISION BY CURTIS"
url: "https://page.curtis.at"
baseurl: "/"
facebook_username: "visionbycurtis"
#twitter_username: ""
instagram_username: "vision_by_curtis"
github_username:  "visionbycurtis"
#deviantart_username: ""
#flickr_username: ""
#discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   Vision by Curtis Fotograf aus Neusiedl am See
  avatar: avatar.png
  favicon: favicon.ico
  info: "Fotograf aus Neusiedl am See. Spezialisiert auf Portrait, Akt, Hochzeiten und Events. Kreative Fotografie mit Leidenschaft."
  location: Neusiedl am See, Austria

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - PORTFOLIO: "https://page.curtis.at/portfolio/"
  - ANGEBOTE: "https://page.curtis.at/angebote/"  
  #- JOURNAL: "https://page.curtis.at/journal/"
  - ABOUT: "https://page.curtis.at/about/"
  #- CONTACT: "https://page.curtis.at/contact/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
